### ISSUE TITLE
Feature Request: Support for Adafruit Qt Py RP2040

### ISSUE THREAD

**Issue by xtagon** [CoreElectronics/CE-PiicoDev-Unified#18]
Hi,

Is it possible to use modify the Unified I2C module to work with the Adafruit Qt Py RP2040 with CircuitPython? It has a built in `busio.IC2` but I'm not sure how to implement the read/write functions for PiicoDev specifically, or how to properly test it.

Thanks,

Justin

**Comment by xtagon** [comment]
Got it working via https://forum.core-electronics.com.au/t/piicodev-rfid-in-circuitpython/19055/15

**Comment by CoreProduction** [comment]
Great that you found our forum with the solution @xtagon - thanks for closing the loop here so other people interested in CircuitPython will be able to find it 🙏
