### ISSUE TITLE
PiicoDev Unified RP2040 I2C pin selection

### ISSUE THREAD

**Issue by LiamHowell** [CoreElectronics/CE-PiicoDev-Unified#6]
Hi Core!

Redefining the SDA and SCL pins using a call to i2c_create_unified cause the pins to remain locked into pin 8 and 9, causing an 'Errno 5'.

Faults occur on the:
Rapsberry Pi Pico
Badger2040

Raised from forum topic: https://forum.core-electronics.com.au/t/picodev-bme280-and-pimoroni-badger-i2c-intermittent/14279/8

**Comment by CoreProduction** [comment]
I've also noticed in passing that when pins are defined eg. `sda=Pin(4), scl=Pin(5)` the device may still work when plugged into pins 8,9, but not at the pins defined.

We'll have to take a deep dive on this one

**Comment by graham-mitchell-vcs** [comment]
Nice find @LiamHowell

**Comment by CoreProduction** [comment]
This issue is resolved - i've run an exhaustive test on a Pico + Pico W and each behave as they ought to. I noticed that when changing between pin definitions I had to power cycle the Pico, presumably to reset the hardware peripheries.

The specifics of the test are documented on the [Core Electronics forum](https://forum.core-electronics.com.au/t/piicodev-tmp117-could-not-communicate/15647/20) and the code is replicated below.

```python
# PiicoDev TMP117 minimal example code
# This program reads the temperature from the PiicoDev TMP117 precision temperature sensor
# and displays the result in Degrees Celsius, Farenheit and Kelvin

from PiicoDev_TMP117 import PiicoDev_TMP117
from PiicoDev_Unified import sleep_ms # cross-platform compatible sleep function
from machine import Pin

### BUS 1
# tempSensor = PiicoDev_TMP117(1,sda=Pin(26), scl=Pin(27), freq=100000) # works

# tempSensor = PiicoDev_TMP117(1,sda=Pin(18), scl=Pin(19), freq=100000) # works

# tempSensor = PiicoDev_TMP117(1,sda=Pin(14), scl=Pin(15), freq=100000) # works

# tempSensor = PiicoDev_TMP117(1,sda=Pin(10), scl=Pin(11), freq=100000) # works

# tempSensor = PiicoDev_TMP117(1,sda=Pin(6), scl=Pin(7), freq=100000) # works

# tempSensor = PiicoDev_TMP117(1,sda=Pin(2), scl=Pin(3), freq=100000) # works


### BUS 0

# tempSensor = PiicoDev_TMP117(0,sda=Pin(8), scl=Pin(9), freq=100000) # works

# tempSensor = PiicoDev_TMP117(0,sda=Pin(4), scl=Pin(5), freq=100000) # works

# tempSensor = PiicoDev_TMP117(0,sda=Pin(12), scl=Pin(13), freq=100000) # works

# tempSensor = PiicoDev_TMP117(0,sda=Pin(20), scl=Pin(21), freq=100000) # works

tempSensor = PiicoDev_TMP117(0,sda=Pin(16), scl=Pin(17), freq=100000) # works


while True:
    # Read and print the temperature in various units
    tempC = tempSensor.readTempC() # Celsius

    
    # Convert temperature into a string and print the data
    print(str(tempC) + " °C")
    
    sleep_ms(1000) # delay 1 second


```
